// This file is auto-generated by Convex
// It will be updated when you run `npx convex dev`

import type { ApiFromModules } from "convex/server";
import type * as bookings from "../bookings";
import type * as customers from "../customers";
import type * as organizations from "../organizations";
import type * as reviews from "../reviews";
import type * as seed from "../seed";
import type * as services from "../services";

const api: ApiFromModules<{
  bookings: typeof bookings;
  customers: typeof customers;
  organizations: typeof organizations;
  reviews: typeof reviews;
  seed: typeof seed;
  services: typeof services;
}> = {} as any;

export { api };