// This file is auto-generated by Convex
// It will be updated when you run `npx convex dev`

export type Id<T extends string> = string & { __tableName: T };

export type Doc<T extends string> = {
  _id: Id<T>;
  _creationTime: number;
};

export type WithoutSystemFields<T> = Omit<T, "_id" | "_creationTime">;

export interface TableNames {
  organizations: true;
  services: true;
  customers: true;
  bookings: true;
  reviews: true;
}